### ISSUE TITLE
Bind to the required fraction of Kollider API

### ISSUE THREAD

**Issue by NCrashed** [standardsats/kollider-client#1]
The task is to follow the https://docs-api.kollider.xyz/ and implement, first, the Rest API with HMAC signature authentication and then the WebSocket part.

- [x] - package backbone with tests from swagger and basic CLI
- [x] - bind all REST endpoints
- [x] - bind WebSocket part

**Comment by NCrashed** [comment]
The first CLI version that can query `/market/products` endpoint 65b1389664f98cd583e891d74ebdbd6734613f84

**Comment by somes731** [comment]
Building REST is not a priority now, right?

**Comment by NCrashed** [comment]
Anyway, I have binded it. It was a good tutorial on what the platform could perform. The important left that binds WebSocket messages. I think, that the demo CLI for the WebSocket binding should support some basic interactive commands when the socket is opened (actions from https://docs-api.kollider.xyz/#tag/Websockets).

**Comment by NCrashed** [comment]
All known API is covered for now.
